global:
  scrape_interval: 1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
      - static_configs:
        - targets: [ "host.docker.internal:9093" ]

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: "BE_Project"
    static_configs:
      - targets: ["localhost:9090"]
      - targets: ["host.docker.internal:3005"]