global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email-notifications'


receivers:
- name: 'email-notifications'
  email_configs:
  - to: <reciever-email-here>
    from: <sender-email-here>
    smarthost: <your-configured-SMTPhost>
    auth_username: <sender-username(generally same as sender email)>
    auth_password: <Your-Authentication-Password>
    auth_identity: <Your-Authentication-Identity>
    tls_config:
      insecure_skip_verify: true









